In [1]:
import numpy as np

# Create the first 1-dimensional array


In [2]:
a = np.arange(16).reshape(2, 2, 4)
print(a)

print(a.shape)

print(a.ndim)

print(a.size)

print(a.dtype.name)

print(a.itemsize) #size of each element

print(a.nbytes) #total size of the array equals itemsize into size

print(a.T) #transpose

print(a.real) #ral numbers

print(a.imag) #imaginary numbers

print(a.flat) #A 1-D iterator over the array.

print(a.ctypes) #An object to simplify the interaction of the array with ctypes.

print(type(a))

b = np.array([6, 7, 8])
print(b)

type(b)


[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
(2, 2, 4)
3
16
int32
4
64
[[[ 0  8]
  [ 4 12]]

 [[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]]
<class 'numpy.ndarray'>
[6 7 8]


numpy.ndarray

Array Creation

In [3]:
import numpy as np
from numpy import pi
b = np.array([2, 3, 4])

print(b)
print(b.dtype)

c = np.array([1.2, 3.5, 5.1])
print(c.dtype)

d = np.array([(1.5, 2, 3), (4, 5, 6)])
print(d)
print(d.dtype)

e = np.array([(1.5, 2, 3), (4, 5, 6), (7,8,9)])
print(e)
print(e.dtype)

#The type of the array can also be explicitly specified at creation time:

f = np.array([[1, 2], [3, 4]], dtype=complex)
print(f.dtype)

array3 = np.linspace(0, pi, 3)
print(array3)
print(array3.dtype.name)

[2 3 4]
int32
float64
[[1.5 2.  3. ]
 [4.  5.  6. ]]
float64
[[1.5 2.  3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]]
float64
complex128
[0.         1.57079633 3.14159265]
float64


In [35]:


# Define a function to generate values
def func(i, j):
    return i + j

# Create a 3x3 array using the function
array_from_func = np.fromfunction(func, (3, 3), dtype=int)
print(array_from_func)


[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [36]:
# First, create a binary file for demonstration purposes
data = np.arange(10, dtype=np.float32)
data.tofile('data.bin')

# Now, read the binary file into an array
array_from_file = np.fromfile('data.bin', dtype=np.float32)
print(array_from_file)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [37]:
# Create a buffer object (e.g., bytes)
buffer = b'\x01\x02\x03\x04'

# Create an array from the buffer
array_from_buffer = np.frombuffer(buffer, dtype=np.uint8)
print(array_from_buffer)


[1 2 3 4]


In [38]:
# Create a string of bytes
byte_string = b'1 2 3 4'

# Create an array from the string
array_from_string = np.fromstring(byte_string, dtype=int, sep=' ')
print(array_from_string)


[1 2 3 4]


In [4]:
g = np.zeros((3, 4))
h = np.ones((2, 3, 4), dtype=np.int16)
i = np.empty((2, 3)) 
#i = np.full((2, 3)) 
#Creating arrays from existing data: using fromfunction(), fromfile(), frombuffer(), and fromstring()
print(g,h,i)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]] [[1.5 2.  3. ]
 [4.  5.  6. ]]


In [5]:
j = np.arange(10, 30, 5)

k = np.arange(0, 2, 0.3) 

l = np.arange(24).reshape(2, 3, 4)  # 3d array
print(l)
print(j,k)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[10 15 20 25] [0.  0.3 0.6 0.9 1.2 1.5 1.8]


Basic Operations

Arithmetic Operations

In [6]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
c = a - b
print(c)
d = b**2
print(d)

[20 29 38 47]
[0 1 4 9]


In [7]:
array1 = np.array([1, 2, 3, 4, 5])

# Create the second 1-dimensional array
array2 = np.array([6, 7, 8, 9, 10])

print("Array 1:", array1)
print("Array 2:", array2)
c = []
for i in range(len(array1)):
    c.append(array1[i]*array2[i])

d = array2*array1
f = array2/array1
g = array2%array1
h = array2**array1
print(c)
print(d)
print(f)
print(g)
print(h)

Array 1: [1 2 3 4 5]
Array 2: [ 6  7  8  9 10]
[6, 14, 24, 36, 50]
[ 6 14 24 36 50]
[6.         3.5        2.66666667 2.25       2.        ]
[0 1 2 1 0]
[     6     49    512   6561 100000]


Unary Operations:

In [8]:
print(array2.sum())
print(array2.min())
print(array2.max())
print(array2.cumsum())

40
6
10
[ 6 13 21 30 40]


Statistical Operations

In [9]:
print(array2.mean())
print(array2.std())
print(array2.var())

8.0
1.4142135623730951
2.0


Comparison Operations:



In [10]:
print(array2 > array1)
print(array1 == array2)
print(array2.any()) #Any true elements
print(array1.all()) #All true elements

#Stacking together different arrays
print(np.concatenate((array1, array2)))
print(np.vstack((array1, array2)))
print(np.hstack((array1, array2)))
print(np.split(array2, [2] ))
print(np.hsplit(array2, [3]))
#print(np.vsplit(array2, [4]))

[ True  True  True  True  True]
[False False False False False]
True
True
[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]
[array([6, 7]), array([ 8,  9, 10])]
[array([6, 7, 8]), array([ 9, 10])]


In [11]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
print(A * B)     # elementwise product

print(A @ B)     # matrix product
print(np.dot(array1, array2)) #dot product
A.dot(B)  # another matrix product


[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
130


array([[5, 4],
       [3, 4]])

Indexing and Slicing:

In [12]:
print(array2[2:4])
print(array2[2:5:2])
print(array2[array2 > 7])
print(array2[[0, 1, 2]])

print(array2[:6:2])

print(array2[::-1])

for i in array2:
    print(i**(1 / 3.))

[8 9]
[ 8 10]
[ 8  9 10]
[6 7 8]
[ 6  8 10]
[10  9  8  7  6]
1.8171205928321397
1.912931182772389
2.0
2.080083823051904
2.154434690031884


Indexing and Slicing: 2D ARRAY

In [13]:
def f(x, y):
    return 10 * x + y

b = np.fromfunction(f, (5, 4), dtype=int)
print(b)

print(b[2, 3])
print(b[0:5, 1]) # each row in the second column of b
print(b[:, 1])    # equivalent to the previous example
print(b[1:3, :])  # each column in the second and third row of b
print(b[-1])   # the last row. Equivalent to b[-1, :]


[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
23
[ 1 11 21 31 41]
[ 1 11 21 31 41]
[[10 11 12 13]
 [20 21 22 23]]
[40 41 42 43]


Indexing and Slicing: 3D ARRAY

In [14]:
c = np.array([[[  0,  1,  2],  # a 3D array (two stacked 2D arrays)
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])
print(c.shape)
#2nd array to print
print(c[1, ...])  
print(c[1, :, :]) 
print(c[1])

print(c[..., 2])  
print(c[:, :, 2])


(2, 2, 3)
[[100 101 102]
 [110 112 113]]
[[100 101 102]
 [110 112 113]]
[[100 101 102]
 [110 112 113]]
[[  2  13]
 [102 113]]
[[  2  13]
 [102 113]]


Iterating over multidimensional arrays

In [15]:
for row in b:
    print(row)

for element in b.flat:
    print(element)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]
0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [16]:

# Creating a 1D array
array_1d = np.array([1, 2, 3, 4, 5])

# Accessing elements by index
print(array_1d[0])  # Output: 1
print(array_1d[-1])  # Output: 5

# Slicing
print(array_1d[1:4])  # Output: [2 3 4]
print(array_1d[:3])   # Output: [1 2 3]
print(array_1d[2:])   # Output: [3 4 5]


1
5
[2 3 4]
[1 2 3]
[3 4 5]


In [17]:
# Creating a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Accessing elements by index
print(array_2d[0, 0])  # Output: 1
print(array_2d[1, 2])  # Output: 6

# Slicing
print(array_2d[0, 1:])  # Output: [2 3]
print(array_2d[:2, :2]) # Output: [[1 2]
                        #          [4 5]]


1
6
[2 3]
[[1 2]
 [4 5]]


Random and Linspace

In [18]:
rg = np.random.default_rng(1)  # create instance of default random number generator
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))
a *= 3
print(a)
b += a
print(b)

[[3 3 3]
 [3 3 3]]
[[3.51182162 3.9504637  3.14415961]
 [3.94864945 3.31183145 3.42332645]]


In [19]:
from numpy import pi
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, pi, 3)
print(a,b)
print(b.dtype.name)

c = a + b
c
print(c)
c.dtype.name

d = np.exp(c * 1j)
print(d)
print(d.dtype.name)

[1 1 1] [0.         1.57079633 3.14159265]
float64
[1.         2.57079633 4.14159265]
[ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j]
complex128


Universal Functions

In [20]:
B = np.arange(3)
print(B)

print(np.exp(B))
print(np.sqrt(B))
C = np.array([2., -1., 4.])
print(np.add(B, C))


[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]
[2. 0. 6.]


In [21]:
b = np.arange(12).reshape(3, 4)
print(b)

print(b.sum(axis=0))     # sum of each column

print(b.min(axis=1))     # min of each row

print(b.cumsum(axis=1))  # cumulative sum along each row

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[0 4 8]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [22]:
a = rg.random((2, 3))
print(a)

print(a.sum())

print(a.min())

print(a.max())


[[0.82770259 0.40919914 0.54959369]
 [0.02755911 0.75351311 0.53814331]]
3.1057109529998157
0.027559113243068367
0.8277025938204418


Changing the shape of an array

In [23]:
a = np.floor(10 * rg.random((3, 4)))
print(a)
print(a.shape)
print(a.ravel())  # returns the array, flattened

print(a.reshape(6, 2))  # returns the array with a modified shape

#The reshape function returns its argument with a modified shape, whereas the ndarray.resize method modifies the array itself:


[[3. 7. 3. 4.]
 [1. 4. 2. 2.]
 [7. 2. 4. 9.]]
(3, 4)
[3. 7. 3. 4. 1. 4. 2. 2. 7. 2. 4. 9.]
[[3. 7.]
 [3. 4.]
 [1. 4.]
 [2. 2.]
 [7. 2.]
 [4. 9.]]


In [30]:
from numpy import newaxis
a = np.floor(10 * rg.random((3, 4)))
print(a)
print(np.column_stack((2, 6)))  # with 2D arrays

c = np.array([4., 2.])
b = np.array([3., 8.])
print(np.column_stack((c, b)))  # returns a 2D array

print(np.vstack((c, b)))
print(np.hstack((c, b)))
print(np.split(c, [2] ))
print(np.hsplit(c, [3]))

print(a[:, newaxis]) # view `a` as a 2D column vector

#np.row_stack is same as np.vstack


[[1. 6. 3. 7.]
 [6. 4. 8. 6.]
 [8. 3. 5. 1.]]
[[2 6]]
[[4. 3.]
 [2. 8.]]
[[4. 2.]
 [3. 8.]]
[4. 2. 3. 8.]
[array([4., 2.]), array([], dtype=float64)]
[array([4., 2.]), array([], dtype=float64)]
[[[1. 6. 3. 7.]]

 [[6. 4. 8. 6.]]

 [[8. 3. 5. 1.]]]


Stacking together different arrays

In [32]:
a = np.floor(10 * rg.random((2, 2)))
b = np.floor(10 * rg.random((2, 2)))
print(a)
print(b)
print(np.vstack((a, b)))
print(np.hstack((a, b)))

[[3. 4.]
 [6. 4.]]
[[5. 8.]
 [7. 3.]]
[[3. 4.]
 [6. 4.]
 [5. 8.]
 [7. 3.]]
[[3. 4. 5. 8.]
 [6. 4. 7. 3.]]


Splitting one array into several smaller ones

In [34]:
a = np.floor(10 * rg.random((2, 12)))
print(a)
print(np.hsplit(a, 3)) # Split `a` into 3
print(np.hsplit(a, (3, 4))) # Split `a` after the third and the fourth column

[[5. 1. 9. 4. 2. 8. 1. 7. 1. 3. 2. 8.]
 [3. 9. 6. 6. 5. 3. 3. 9. 2. 9. 7. 3.]]
[array([[5., 1., 9., 4.],
       [3., 9., 6., 6.]]), array([[2., 8., 1., 7.],
       [5., 3., 3., 9.]]), array([[1., 3., 2., 8.],
       [2., 9., 7., 3.]])]
[array([[5., 1., 9.],
       [3., 9., 6.]]), array([[4.],
       [6.]]), array([[2., 8., 1., 7., 1., 3., 2., 8.],
       [5., 3., 3., 9., 2., 9., 7., 3.]])]


Copies and Views

In [39]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
b = a            # no new object is created
b is a           # a and b are two names for the same ndarray object

True

In [40]:
def f(x):
    print(id(x))

id(a)  # id is a unique identifier of an object 

1704267210000

View or Shallow Copy

In [45]:
c = a.view()
c is a

c.base is a            # c is a view of the data owned by a

c.flags.owndata

c = c.reshape((2, 6))  # a's shape doesn't change
print(c)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [46]:
s = a[:, 1:3]
s[:] = 10  # s[:] is a view of s. Note the difference between s = 10 and s[:] = 10
print(a)

[[ 0 10 10  3]
 [ 4 10 10  7]
 [ 8 10 10 11]]


Basic Broadcasting:

In [49]:
import numpy as np

# Create a 2D array and a 1D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_1d = np.array([10, 20, 30])

# Broadcasting the 1D array to match the 2D array shape
result = array_2d + array_1d
print(result)

#Broadcasting with Different Shapes:
# Create a 2D array and a scalar
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 10

# Broadcasting the scalar to match the 2D array shape
result = array_2d + scalar
print(result)

#Broadcasting Across Higher Dimensions:
# Create a 3D array and a 2D array
array_3d = np.array([[[1], [2], [3]], [[4], [5], [6]]])
array_2d = np.array([[10, 20, 30]])

# Broadcasting the 2D array to match the 3D array shape
result = array_3d + array_2d
print(result)



[[11 22 33]
 [14 25 36]]
[[11 12 13]
 [14 15 16]]
[[[11 21 31]
  [12 22 32]
  [13 23 33]]

 [[14 24 34]
  [15 25 35]
  [16 26 36]]]


In [53]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape
a2 = a[np.newaxis, :]
a2.shape



(1, 6)